name: Test integration for Browserstack

on :
  workflow_dispatch:

env:
  APP_DIR:  ITTH_Weekday_October2023

jobs:
  build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

      - run: mvn clean install -PTestSample
        working-directory: ITTH_Weekday_October2023

         

     


    

