name: Test integration for Browserstack

on :
  workflow_dispatch:
   inputs:
     mavenProfile:
       required: true
     GitHubValue:
       required: true

     

jobs:
  build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

      - run: mvn clean install -DGitHubValue=${{ github.event.inputs.GitHubValue }} -P${{ github.event.inputs.mavenProfile }} 

         

     


    

